//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCM.ServiciosInternet.Site.Entity.www.gana.kleenbebe.com_1.BD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string IdTicket { get; set; }
        public string UID { get; set; }
        public decimal Amount { get; set; }
        public int SKU { get; set; }
        public string UrlPhoto { get; set; }
        public int Attempts { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Competitor Competitor { get; set; }
        public virtual Product Product { get; set; }
    }
}
