//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCM.ServiciosInternet.Site.Entity.www.gana.kleenbebe.com_1.BD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGame
    {
        public int PivotDayId { get; set; }
        public long Id { get; set; }
        public Nullable<int> IdGameInfo { get; set; }
        public Nullable<System.DateTime> GameDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string IdTicket { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
