/****** Script for SelectTopNRows command from SSMS  ******/
-- --------------------------------------------------
-- Date Created: 09/09/2021 
-- Author: Eng. JORGE FLORES MIGUEL   jorge_kain@yahoo.com
-- Description:  genarate dbo.vwTicketByPivotDay
-- --------------------------------------------------

DROP VIEW IF EXISTS dbo.vwTicketByPivotDay; 
GO

CREATE VIEW dbo.vwTicketByPivotDay
AS
SELECT [PivotDayId]
      ,[IdTicket]
      ,[GameDescription]
      ,[TicketDate]
      ,[TicketAmount]
      ,[BestTime]
      ,[Product]
      ,[ProductSize]
      ,[TicketAttempts]
      ,[TicketPath]
      ,[CompetitorUID]
      ,[CompetitorFirstName]
      ,[CompetitorLastName]
      ,[CompetitorEmail]
      ,[CompetitorBirthDay]
      ,[CompetitorPhone]
      ,[BestTimeIdTicket]
	  ,[IsValid]
	  ,[IsWinner]
	  ,[UpdatedBy]
	  ,[LastUpdate] 
  FROM [dbo].[TicketByPivotDay_1]
UNION ALL
SELECT [PivotDayId]
      ,[IdTicket]
      ,[GameDescription]
      ,[TicketDate]
      ,[TicketAmount]
      ,[BestTime]
      ,[Product]
      ,[ProductSize]
      ,[TicketAttempts]
      ,[TicketPath]
      ,[CompetitorUID]
      ,[CompetitorFirstName]
      ,[CompetitorLastName]
      ,[CompetitorEmail]
      ,[CompetitorBirthDay]
      ,[CompetitorPhone]
      ,[BestTimeIdTicket]
	  ,[IsValid]
	  ,[IsWinner]
	  ,[UpdatedBy]
	  ,[LastUpdate] 
  FROM [dbo].[TicketByPivotDay_2]
  UNION ALL
SELECT [PivotDayId]
      ,[IdTicket]
      ,[GameDescription]
      ,[TicketDate]
      ,[TicketAmount]
      ,[BestTime]
      ,[Product]
      ,[ProductSize]
      ,[TicketAttempts]
      ,[TicketPath]
      ,[CompetitorUID]
      ,[CompetitorFirstName]
      ,[CompetitorLastName]
      ,[CompetitorEmail]
      ,[CompetitorBirthDay]
      ,[CompetitorPhone]
      ,[BestTimeIdTicket]
	  ,[IsValid]
	  ,[IsWinner]
	  ,[UpdatedBy]
	  ,[LastUpdate] 
  FROM [dbo].[TicketByPivotDay_3]
  UNION ALL
SELECT [PivotDayId]
      ,[IdTicket]
      ,[GameDescription]
      ,[TicketDate]
      ,[TicketAmount]
      ,[BestTime]
      ,[Product]
      ,[ProductSize]
      ,[TicketAttempts]
      ,[TicketPath]
      ,[CompetitorUID]
      ,[CompetitorFirstName]
      ,[CompetitorLastName]
      ,[CompetitorEmail]
      ,[CompetitorBirthDay]
      ,[CompetitorPhone]
      ,[BestTimeIdTicket]
	  ,[IsValid]
	  ,[IsWinner]
	  ,[UpdatedBy]
	  ,[LastUpdate] 
  FROM [dbo].[TicketByPivotDay_4]
  UNION ALL
SELECT [PivotDayId]
      ,[IdTicket]
      ,[GameDescription]
      ,[TicketDate]
      ,[TicketAmount]
      ,[BestTime]
      ,[Product]
      ,[ProductSize]
      ,[TicketAttempts]
      ,[TicketPath]
      ,[CompetitorUID]
      ,[CompetitorFirstName]
      ,[CompetitorLastName]
      ,[CompetitorEmail]
      ,[CompetitorBirthDay]
      ,[CompetitorPhone]
      ,[BestTimeIdTicket]
	  ,[IsValid]
	  ,[IsWinner]
	  ,[UpdatedBy]
	  ,[LastUpdate] 
  FROM [dbo].[TicketByPivotDay_5]
  UNION ALL
SELECT [PivotDayId]
      ,[IdTicket]
      ,[GameDescription]
      ,[TicketDate]
      ,[TicketAmount]
      ,[BestTime]
      ,[Product]
      ,[ProductSize]
      ,[TicketAttempts]
      ,[TicketPath]
      ,[CompetitorUID]
      ,[CompetitorFirstName]
      ,[CompetitorLastName]
      ,[CompetitorEmail]
      ,[CompetitorBirthDay]
      ,[CompetitorPhone]
      ,[BestTimeIdTicket]
	  ,[IsValid]
	  ,[IsWinner]
	  ,[UpdatedBy]
	  ,[LastUpdate] 
  FROM [dbo].[TicketByPivotDay_6]
  UNION ALL
SELECT [PivotDayId]
      ,[IdTicket]
      ,[GameDescription]
      ,[TicketDate]
      ,[TicketAmount]
      ,[BestTime]
      ,[Product]
      ,[ProductSize]
      ,[TicketAttempts]
      ,[TicketPath]
      ,[CompetitorUID]
      ,[CompetitorFirstName]
      ,[CompetitorLastName]
      ,[CompetitorEmail]
      ,[CompetitorBirthDay]
      ,[CompetitorPhone]
      ,[BestTimeIdTicket]
	  ,[IsValid]
	  ,[IsWinner]
	  ,[UpdatedBy]
	  ,[LastUpdate] 
  FROM [dbo].[TicketByPivotDay_7]
  UNION ALL
SELECT [PivotDayId]
      ,[IdTicket]
      ,[GameDescription]
      ,[TicketDate]
      ,[TicketAmount]
      ,[BestTime]
      ,[Product]
      ,[ProductSize]
      ,[TicketAttempts]
      ,[TicketPath]
      ,[CompetitorUID]
      ,[CompetitorFirstName]
      ,[CompetitorLastName]
      ,[CompetitorEmail]
      ,[CompetitorBirthDay]
      ,[CompetitorPhone]
      ,[BestTimeIdTicket]
	  ,[IsValid]
	  ,[IsWinner]
	  ,[UpdatedBy]
	  ,[LastUpdate] 
  FROM [dbo].[TicketByPivotDay_8];